# Generated by Django 5.0.3 on 2024-04-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('nit', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('petition_type', models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo')], max_length=20)),
                ('state', models.CharField(choices=[('Recibido', 'Recibido'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('petition_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.clients')),
            ],
        ),
        migrations.CreateModel(
            name='PetitionResponses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.pqr')),
            ],
        ),
    ]
