# Generated by Django 5.0.3 on 2024-04-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('nit', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_solicitud', models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo')], max_length=20)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.clients')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas_solicitudes',
            fields=[
                ('historial_solicitudes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_respuesta', models.DateTimeField()),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('pqrs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.pqr')),
            ],
        ),
    ]
